### ISSUE TITLE
Can't delete U32 filters

### ISSUE THREAD

**Issue by ianling** [florianl/go-tc#17] opened 2020-10-05 21:04 UTC
If I use `...Filter().Get(...)` to retrieve a filter, I cannot then delete that filter: `Filter().Delete(&filter)`

From the command line, I am able to add and delete filters as expected:

```
$ tc filter add dev ens5 parent 0: protocol ip prio 1 u32 match ip dst 199.200.15.170 match ip dport 28145 0xffff action mirred egress redirect dev ifb0
$ tc filter del dev ens5 parent 0: handle 800::801 prio 1 u32
```

But I can't figure out how to accomplish the same thing in go-tc.

```
filterQuery := tc.Msg{
	Ifindex: uint32(2),
	Parent:  tc.HandleIngress,
}
filters, _ := tcgo.Filter().Get(&filterQuery)
filter := filters[0]
err := tcgo.Filter().Delete(&filter)  // error: "argument cannot be altered"

filter2 := tc.Object{
	tc.Msg{
		Handle:  filter.Handle,
		Parent:  filter.Parent,
		Ifindex: filter.Ifindex,
	},
	tc.Attribute{
		Kind: filter.Kind,
		U32: filter.U32,
	},
}
err = tcgo.Filter().Delete(&filter2)  // error: "netlink receive: no such file or directory"
```

Do you have any idea how I can delete a filter via go-tc?

**Comment by ianling** [comment] 2020-10-05 21:29
I found that commenting out the "Handle:" and "U32:" lines in the example above allows the delete to succeed, but obviously that makes it match filters I wasn't intending to delete:

```
filter2 := tc.Object{
	tc.Msg{
		//Handle:  filter.Handle,
		Parent:  filter.Parent,
		Ifindex: filter.Ifindex,
	},
	tc.Attribute{
		Kind: filter.Kind,
		//U32: filter.U32,
	},
}
err = tcgo.Filter().Delete(&filter2)  // works! but deletes too many filters
```

**Comment by florianl** [comment] 2023-05-24 18:54
Thanks for reporting the issue @sanfern 

As filters of type U32 are different from filters of type BPF, I would appreceate to handle this in a dedicated issue.
But thanks for reporting with a minimal reproducable program :pray: 

Did you try to list attached filters with something alone the following lines?
```
tcgo.Filter().Get(&tc.Msg{
		Family:  unix.AF_UNSPEC,
		Ifindex: uint32(devID.Index),
		Handle:  0x0,
		Parent:  core.BuildHandle(tc.HandleRoot, tc.HandleMinIngress),
	})
```
If you compare the reported filters with your initial given input, you will notice differences. In particular pay attention to `tc.Msg.Info`.
As a consequence, if you take the reported filter and use the reported object as input to the `Delete()` function, you should be able to delete filter.

With regard to the inital request from @ianling: I would be happy to go forward if answers to the questions in https://github.com/florianl/go-tc/issues/17#issuecomment-704467961 are provided. Otherwise I will in the following months close this issue because of missing response.

**Comment by RealFatCat** [comment] 2023-06-05 14:21
@florianl HI, I have the same issue with Nat action, and the reason is [this check](https://github.com/florianl/go-tc/blob/main/m_nat.go#L43).

Mirred action have [the same check](https://github.com/florianl/go-tc/blob/main/m_mirred.go#L68).

So for now, we can't just `Filter().Get()` U32 filters with NAT and Mirred (may be some others too) actions.

To repoduce, add some filters with NAT action to dummy0:
```
sudo ip l add dev dummy0 type dummy
sudo tc qdisc  add dev dummy0 ingress
sudo tc filter add dev  dummy0 parent ffff: pref 10 u32 match ip dst 192.168.1.1/24 action nat ingress 127.1.1.1/16 127.0.0.1 # just as example
```
and run this code:

```package main

import (
	"fmt"
	"net"
	"os"
	"syscall"

	"github.com/mdlayher/netlink"

	"github.com/florianl/go-tc"
)

const (
	linkName = "dummy0"
)

func main() {
	// open a rtnetlink socket
	rtnl, err := tc.Open(&tc.Config{})
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not open rtnetlink socket: %v\n", err)
		return
	}
	defer func() {
		if err := rtnl.Close(); err != nil {
			fmt.Fprintf(os.Stderr, "could not close rtnetlink socket: %v\n", err)
		}
	}()

	err = rtnl.SetOption(netlink.ExtendedAcknowledge, true)
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not set option ExtendedAcknowledge: %v\n", err)
		return
	}

	l, err := net.InterfaceByName(linkName)
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get interface: %v\n", err)
		return
	}

	msg := tc.Msg{
		Family:  syscall.AF_UNSPEC,
		Ifindex: uint32(l.Index),
		Parent:  tc.HandleRoot,
	}

	filters, err := rtnl.Filter().Get(&msg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not get filters: %v\n", err)
		return
	}

	for _, f := range filters {
		if f.Attribute.U32 != nil && f.Attribute.U32.Actions != nil {
			err := rtnl.Filter().Delete(&f)
			if err != nil {
				fmt.Println(err)
			}
		}
	}
}
```

**Comment by florianl** [comment] 2023-06-05 18:33
Thanks for reporting. I will try to reproduce it and investigate.

**Comment by florianl** [comment] 2023-06-10 08:09
Filter argument checking was simplified in https://github.com/florianl/go-tc/pull/120. If you run in further issues, pelase open a new issue.

**Closed by florianl** 2023-06-10 08:09 UTC
Labels: needs investigation, missing information
